# Default values for dapp-dsp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


eosnode:
  enabled: true
  replicaCount: 1
  persistence:
    enabled: true
    size: 1000Gi
  # Default values for dapp-dsp.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.
  enabled: true
  replicaCount: 1
  image:
    repository: yan047/eos
    tag: v1.6.0
    pullPolicy: Always
  
  service:
    port: 8888
    type: LoadBalancer
    loadBalancerSourceRanges: "0.0.0.0/0"
   
  # The argument passed to nodeos 
  args:
    - --max-transaction-time 
    - "5000"
    - --abi-serializer-max-time-ms 
    - "15000"
    
  genesis:
    initial_timestamp: "2018-09-12T16:21:19.132"
    signatureProvider: EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV=KEY:5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3
    initial_configuration: 
      max_block_net_usage: 1048576 
      target_block_net_usage_pct: 1000
      max_transaction_net_usage: 524288
      base_per_transaction_net_usage: 12
      net_usage_leeway: 500
      context_free_discount_net_usage_num: 20
      context_free_discount_net_usage_den: 100
      max_block_cpu_usage: 200000
      target_block_cpu_usage_pct: 1000
      max_transaction_cpu_usage: 150000
      min_transaction_cpu_usage: 100
      max_transaction_lifetime: 3600
      deferred_trx_expiration_window: 600
      max_transaction_delay: 3888000
      max_inline_action_size: 4096
      max_inline_action_depth: 4
      max_authority_depth: 6
      
  persistence:
    enabled: true
    ## A manually managed Persistent Volume and Claim
    ## Requires Persistence.Enabled: true
    ## If defined, PVC must be created manually before volume will be bound
    # ExistingClaim:
  
    ## Data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
  
    size: 100Gi
    
  resources: {}  # Optionally specify how much CPU and memory (RAM) each nodeos container needs.
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
    
ipfs:
  enabled: true
  replicaCount: 1
  persistence:
    size: 100Gi
  service:
    type: LoadBalancer
dspnode:
  enabled: true
  replicaCount: 1
  service:
    type: LoadBalancer
  replicaCount: 1
  
  image:
    repository: yan047/eos
    tag: v1.6.0
    pullPolicy: Always

  service:
    port: 8888
    type: LoadBalancer
    loadBalancerSourceRanges: "0.0.0.0/0"