apiVersion: v1
kind: Service
metadata:
  name: {{ include "eosnode.nodeosfullname" . }}
  labels:
    app: {{ include "eosnode.name" . }}
    chart: {{ include "eosnode.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
{{- if eq .Values.service.type "LoadBalancer" }}  
  loadBalancerSourceRanges: 
{{- range $index, $cidr := .Values.service.loadBalancerSourceRanges | split "," }}
    - {{ $cidr }}
{{- end }}
{{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8888
      protocol: TCP
      name: api
    - port: {{ .Values.service.qport }}
      targetPort: 5556
      protocol: TCP
      name: queue
    - port: {{ .Values.service.pport }}
      targetPort: 9876
      protocol: TCP
      name: p2p
  selector:
    app: nodeos
    release: {{ .Release.Name }}
